# Generated by Django 3.2.6 on 2022-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
